<?php
/*
 * APIMATICCalculatorTestcasesLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 09/29/2016
 */

namespace APIMATICCalculatorTestcasesLib\Http;

/**
* HTTP Methods Enumeration
*/
class HttpMethod
{
    const GET = "Get";
    const POST = "Post";
    const PUT = "Put";
    const PATCH = "Patch";
    const DELETE = "Delete";
}