<?php
/*
 * APIMATICCalculatorTestcasesLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 09/29/2016
 */

namespace APIMATICCalculatorTestcasesLib;

use APIMATICCalculatorTestcasesLib\Controllers;

/**
 * APIMATICCalculatorTestcasesLib client class
 */
class APIMATICCalculatorTestcasesClient
{
    /**
     * Constructor with authentication and configuration parameters
     */
    public function __construct($basicAuthUserName = NULL, $basicAuthPassword = NULL)
    {
        Configuration::$basicAuthUserName = $basicAuthUserName ? $basicAuthUserName : Configuration::$basicAuthUserName;
        Configuration::$basicAuthPassword = $basicAuthPassword ? $basicAuthPassword : Configuration::$basicAuthPassword;
    }
 
    /**
     * Singleton access to SimpleCalculator controller
     * @return Controllers\SimpleCalculatorController The *Singleton* instance
     */
    public function getSimpleCalculator()
    {
        return Controllers\SimpleCalculatorController::getInstance();
    }
}